### PR TITLE
v1.5.0 - update output excel

### LINKED ISSUE #23: minor refactor for sanity and readability
this mess of appends could / should be refactored into the initial df creation: https://github.com/eastgenomics/eggd_artemis/blob/d31e869494fa3f441ba17657f34c23cb5b40974d/src/eggd_artemis.py#L785-L801

```
pd.DataFrame([
    {'a': 'Run', 'b' project_name},
    {'a': 'Number of samples in this file:', 'b': sample_count}
    ...
])
```

no idea what I was thinking when I wrote it initially but it ain't great

### PR DESCRIPTION
**Pull request by growland2**
- Update `write_output_file()` to include new outputs (excluded regions and summary text)
- Fix #23

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30)

### CODE REVIEW

**Comment by growland2** [comment]
[completed job](https://platform.dnanexus.com/panx/projects/GkbBjJ04Pqj2Q3J597Q3gKJx/monitor/job/Gp1GgK04PqjF2pYV3k34b5xX) outputting updated artemis file for one sample

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @growland2 and @rklocke)

___
*[`src/eggd_artemis.py` line 636 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0iyrV_CE6dcgYoPQOL:-O0iyrV_CE6dcgYoPQOM:b-ygp3k0) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L636)):*
> ```Python
>         'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], header=None)
> 
>     required_headers.sort()
> ```

why not just sort it above where it's defined to save calling sort?



_Code quote:_
```Python
required_headers.sort()
```
___
*[`src/eggd_artemis.py` line 638 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0iyvwoAHmFppLM8gUn:-O0iyvwoAHmFppLM8gUo:bijh21m) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L638)):*
fyi there's `sort` (which acts in place) and `sorted()` (which returns the sorted list), so this can be one line:
```
>>> foo = sorted([3, 1, 2])
>>> foo
[1, 2, 3]
```



_Code quote:_
```Python
    headers = df.iloc[0, :].tolist()
    headers.sort()
```
___
*[`src/eggd_artemis.py` line 639 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0izCDDE8VE3OjHLlxb:-O0izCDDE8VE3OjHLlxc:b-j7o2y) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L639)):*
what can make debugging easier is showing the error in a message, example here could be:

```
>>> l1 = [1,2,3]
>>> l2=[1,2]
>>> missing = set(l1) - set(l2)
>>> assert not missing, f"missing value: {missing}"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: missing value: {3}
```

vs

```
>>> assert l1 == l2, "not equal"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: not equal
```

as you don't know what is missing



_Code quote:_
```Python
assert required_headers == headers, f"{file_id} doesn't have all the required headers"
```
___
*[`src/eggd_artemis.py` line 641 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j-iA74DzswyYBdjkI:-O0j-iA74DzswyYBdjkJ:b4zxm1m) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L641)):*
> ```Python
>     assert required_headers == headers, f"{file_id} doesn't have all the required headers"
> 
>     df.insert(0, 'a', ["CNV excluded regions"] + [None] * (len(df) - 1))
> ```

why is this `-1`?



_Code quote:_
```Python
df.insert(0, 'a', ["CNV excluded regions"] + [None] * (len(df) - 1))
```
___
*[`src/eggd_artemis.py` line 817 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j-xzj-OYVOmt6Ijrj:-O0j-xzj-OYVOmt6Ijrk:b-lbkkv2) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L817)):*
> ```Python
>                     # Column names/header are read into the first row of df,
>                     # therefore if df length is < 2 it contains no data
>                     if len(file.get('cnv_excluded_regions_df')) < 2:
> ```

do the header lines begin with a hash? If so removing those from the beginning with hash would be more robust in case the number of header lines changes. 



_Code quote:_
```Python
                    # Column names/header are read into the first row of df,
                    # therefore if df length is < 2 it contains no data
                    if len(file.get('cnv_excluded_regions_df')) < 2:
```
___
*[`src/eggd_artemis.py` line 857 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j0EQYBLfnY43vOb-B:-O0j0EQYBLfnY43vOb-C:b-9gtmuv) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L857)):*
> ```Python
>     if qc_url.startswith('http'):
>         qc_url = f'=HYPERLINK("{qc_url}", "{qc_url}")'
> ```

can you add a comment here to indicate that the empty dicts are to force blank lines when dumped to excel for future us to know what this is
___
*[`src/eggd_artemis.py` line 974 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j1XJlCRA0xchotFCb:-O0j1XJlCRA0xchotFCc:b27uwi8) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L974)):*
> ```Python
>         sheet.protection.formatCells = False
> 
>         for row_no in range(1, 5000):
> ```

why is this 3000 -> 5000



_Code quote:_
```Python
5000
```

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jethror1 and @rklocke)

___
*[`src/eggd_artemis.py` line 636 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0iyrV_CE6dcgYoPQOL:-O0mN-hX6OBULIREdywD:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L636)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why not just sort it above where it's defined to save calling sort?
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 638 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0iyvwoAHmFppLM8gUn:-O0mMwK8CIWf6xLzMQ5r:b-7ql1td) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L638)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

fyi there's `sort` (which acts in place) and `sorted()` (which returns the sorted list), so this can be one line:
```
>>> foo = sorted([3, 1, 2])
>>> foo
[1, 2, 3]
```
</blockquote></details>

fixed
___
*[`src/eggd_artemis.py` line 639 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0izCDDE8VE3OjHLlxb:-O0mPBjj8d-YJr7GY2BE:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L639)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what can make debugging easier is showing the error in a message, example here could be:

```
>>> l1 = [1,2,3]
>>> l2=[1,2]
>>> missing = set(l1) - set(l2)
>>> assert not missing, f"missing value: {missing}"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: missing value: {3}
```

vs

```
>>> assert l1 == l2, "not equal"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: not equal
```

as you don't know what is missing
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 641 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j-iA74DzswyYBdjkI:-O0mPCY0BCr6PPZbvLAt:br0y83c) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L641)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why is this `-1`?
</blockquote></details>

The idea is to create a list (which will be inserted as a column) containing first "CNV excluded regions" and then "None" for the rest for the list/column (i.e. length of the column minus the one existing item in the column len(df) - 1) 
___
*[`src/eggd_artemis.py` line 817 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j-xzj-OYVOmt6Ijrj:-O0mPwXD8nHO0giHktkS:b-jbg8zi) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L817)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do the header lines begin with a hash? If so removing those from the beginning with hash would be more robust in case the number of header lines changes.
</blockquote></details>

The headers/columns are derived from the first line of the annotated excluded regions .tsv when it is read in via `read_excluded_regions_to_df()`, this should not reasonably be expected to change and there are no hashes to remove. 
___
*[`src/eggd_artemis.py` line 857 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j0EQYBLfnY43vOb-B:-O0mSiU5AdT5uevZXJPp:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L857)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add a comment here to indicate that the empty dicts are to force blank lines when dumped to excel for future us to know what this is
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 974 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j1XJlCRA0xchotFCb:-O0mSj6H5r2j2MIMx1QR:b-6ywccu) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L974)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why is this 3000 -> 5000
</blockquote></details>

As we are adding in extra lines into the output df (excluded regions, coverage summary) the number of rows which need to be unlocked was increased to account for this

**Review by rklocke — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30)* status: all files reviewed, 10 unresolved discussions (waiting on @growland2 and @jethror1)

___
*[`src/eggd_artemis.py` line 631 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0mWpXUCoFm9HxwlnIN:-O0mWpXUCoFm9HxwlnIO:b-bgjpa2) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L631)):*
> ```Python
>     )
> 
>     # letters a -> i used as columns names to aid concatenation of this df when
> ```

I guess it's letters b -> i rather than a -> i?
___
*[`src/eggd_artemis.py` line 892 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0mY4hy6xLXNStm76n7:-O0mY4hy6xLXNStm76n8:b-nz6nl3) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L892)):*
> ```Python
>         output_fields = {
>             'coverage_url': 'Coverage report',
>             'coverage_summary': 'Coverage summary',
> ```

In the example job, when opening the output in LibreOffice I can only see the first line of the coverage summary and I can't expand the cell because it is protected - is there any way we can make this show multi-line?

___
*[`src/eggd_artemis.py` line 922 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0mYlmv-cELFHHRLM5o:-O0mYlmv-cELFHHRLM5p:br4z8t8) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L922)):*
> ```Python
>                     # could be text or a df which affects how it is added to
>                     # output df
>                     if field == 'cnv_excluded_regions_df':
> ```

In the mock up artemis file we have two empty rows around the excluded regions df and the IGV session link is after the excluded regions df - do we want to update this? Not sure how important it is
___
*[`src/eggd_artemis.py` line 957 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0mXW5d6EchHgoC7eHs:-O0mXW5d6EchHgoC7eHt:b-7rfxl) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L957)):*
> ```Python
>     sheet = writer.sheets['Sheet1']
>     sheet.column_dimensions['A'].width = 55
>     sheet.column_dimensions['B'].width = 155
> ```

should this width of this column be reduced so it matches the mock up artemis file given to scientists? It looks a bit silly atm.. not sure if we should also consider updating the widths of the other columns for the excluded regions df so they look nicer:

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30)* status: all files reviewed, 5 unresolved discussions (waiting on @growland2 and @rklocke)

___
*[`src/eggd_artemis.py` line 974 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j1XJlCRA0xchotFCb:-O0mcoEx2Rf2PdH-aam0:b-d6qm0p) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L974)):*
you can get the actual number of rows and columns with content using `max_row` and `max_column`:

```
>>> writer.sheets['Sheet1'].max_row
35
>>> writer.sheets['Sheet1'].max_column
9
```

you might want to add some buffer onto this, but I don't get the point of just choosing some arbitrarily large number, what is it trying to achieve?
___
*[`src/eggd_artemis.py` line 892 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0mY4hy6xLXNStm76n7:-O0m_V4K-E71t7CB9ABj:b-x50jvz) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L892)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

In the example job, when opening the output in LibreOffice I can only see the first line of the coverage summary and I can't expand the cell because it is protected - is there any way we can make this show multi-line?

</blockquote></details>

not sure if scientists would want it multi line would they? it can get quite long and could make the view much longer, if the use case is just to copy paste then its fine, but obvs if they need to fully read it it should be better

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30)* status: all files reviewed, 5 unresolved discussions (waiting on @rklocke)

___
*[`src/eggd_artemis.py` line 631 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0mWpXUCoFm9HxwlnIN:-O0mbInE0rsU887ks1L4:bey90kd) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L631)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I guess it's letters b -> i rather than a -> i?
</blockquote></details>

'a' is used in the inserted row [see line 641](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L641), I could add an additional comment if you think it would be helpful?
___
*[`src/eggd_artemis.py` line 922 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0mYlmv-cELFHHRLM5o:-O0md5Bl4QquiwbR3s3f:bb9aaki) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L922)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

In the mock up artemis file we have two empty rows around the excluded regions df and the IGV session link is after the excluded regions df - do we want to update this? Not sure how important it is
</blockquote></details>

I'm inclined to leave as is

**Comment by growland2** [comment]
Add functionality to allow the heights/widths of cells to be adjusted when locked

**Review by growland2 — COMMENTED** [review]
Already implemented but didn't realise as it is not functional in Libre Office (but is functional in MS Excel)

> Add functionality to allow the heights/widths of cells to be adjusted when locked

___
*[`src/eggd_artemis.py` line 974 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0j1XJlCRA0xchotFCb:-O0mq91UA6ySC8QJNdjh:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/a411e32ddc662a40e7845a9def4da2e237fef596/src/eggd_artemis.py#L974)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you can get the actual number of rows and columns with content using `max_row` and `max_column`:

```
>>> writer.sheets['Sheet1'].max_row
35
>>> writer.sheets['Sheet1'].max_column
9
```

you might want to add some buffer onto this, but I don't get the point of just choosing some arbitrarily large number, what is it trying to achieve?
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 957 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30#-O0mXW5d6EchHgoC7eHs:-O0nEqiMAiUh1X3HvgeI:bbedyt8) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/04f190394d9b0aecb0471e4b30346e78761ee610/src/eggd_artemis.py#L957)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

should this width of this column be reduced so it matches the mock up artemis file given to scientists? It looks a bit silly atm.. not sure if we should also consider updating the widths of the other columns for the excluded regions df so they look nicer:

</blockquote></details>

Columns widths have now been set for these columns taking into account the maximum possible lengths of each column. [Example job and output](https://platform.dnanexus.com/panx/projects/GkbBjJ04Pqj2Q3J597Q3gKJx/monitor/job/Gp1yKk84Pqj5ZF21ZgjFgYXJ)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30)* status: all files reviewed, 4 unresolved discussions (waiting on @rklocke)

**Review by rklocke — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/30)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @growland2)

**Pull request merged**
