### PR TITLE
Initial PR - app works 

### PR DESCRIPTION
**Pull request by Addy81**
PR opened for initial review

job it works:
https://platform.dnanexus.com/panx/projects/GJFBY1046FxB9j1G4jPPg3kV/data/?scope=project&id.values=file-GJkgfqj4Vv14zkgK4kqZ37F7

Still need to test:
* if only snv path is provided
* if only cnv path is provided (atm this will not have a coverage report)
* if neither provided it fails correctly
* more than one paths

Also need to consider the possibility if given multiple paths the paths containing more than one report

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Addy81)

___
*[`dxapp.json` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwFWoG8pQvt_7-HEBT:-NGwFWoG8pQvt_7-HEBU:bbcunqz) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/dxapp.json#L27)):*
> ```JSON
>     {
>       "name": "url_duration",
>       "label": "Active url duration",
> ```

could we specify that this is in seconds?



_Code quote:_
```JSON
duration
```
___
*[`Readme.md` line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwFso37wK7GK5XqD_D:-NGwFso45PHemhtpJzqb:undefined) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/Readme.md#L7)):*
> ```Markdown
> ## What does this app do?
> 
> Gathers required files and creates file containing urls for to allow file download within CUH & the LGLs.
> ```





_Suggestion:_
```Markdown
urls to allow
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @Addy81)

___
*[`src/eggd_artemis.py` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwGDXA-Nw3cj1fYBJJ:-NGwGDXA-Nw3cj1fYBJK:b-8ktc8g) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L2)):*
> ```Python
> #!/usr/bin/env python
> # eggd_artemis 0.0.1
> ```

1.0.0



_Code quote:_
```Python
0.0.1
```
___
*[`src/eggd_artemis.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwGItIBuqEa417nrS8:-NGwGItIBuqEa417nrS9:byuvamn) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L12)):*
> ```Python
> #
> # DNAnexus Python Bindings (dxpy) documentation:
> #   http://autodoc.dnanexus.com/bindings/python/current/
> ```

Could we remove this stuff which is added by the wizard?



_Code quote:_
```Python
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# See https://documentation.dnanexus.com/developer for documentation and
# tutorials on how to modify this file.
#
# DNAnexus Python Bindings (dxpy) documentation:
#   http://autodoc.dnanexus.com/bindings/python/current/
```
___
*[`src/eggd_artemis.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwGdB69qQ1wgat87WQ:-NGwGdB69qQ1wgat87WR:undefined) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L37)):*
> ```Python
> 
>     Returns:
>         snv_data (dict): Nested ictionary of files with sample name
> ```





_Suggestion:_
```Python
dictionary
```
___
*[`src/eggd_artemis.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwHc3U7zESFn44s4PL:-NGwHc3U7zESFn44s4PM:bvw500j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L154)):*
> ```Python
> 
>         for k,v in gcnv_dict.items():
>             if k.startswith(sample):
> ```

Would it be better to look for `sample_` so that X123 doesn't match X1234?

Should never happen, but no reason not to defend against this



_Code quote:_
```Python
if k.startswith(sample)
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @Addy81)

___
*[`src/eggd_artemis.py` line 364 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwJOuV5vNNg5Y8hjqF:-NGwJOuV5vNNg5Y8hjqG:b-fy86q) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L364)):*
> ```Python
>             for sample,details in data.items():
> 
>                 f.write(f"Sample ID:\t{sample}\n")
> ```

Newline before each sample would make the output format a little nicer imo



_Suggestion:_
```Python
\nSample ID:\t{sample}\n
```

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

___
*[`dxapp.json` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwFWoG8pQvt_7-HEBT:-NGzAMCqDWBNR9nm_IF4:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/dxapp.json#L27)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

could we specify that this is in seconds?
</blockquote></details>

Done
___
*[`Readme.md` line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwFso37wK7GK5XqD_D:-NGzARpvEDc9s_8bGFXs:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/Readme.md#L7)):*
> ```Markdown
> ## What does this app do?
> 
> Gathers required files and creates file containing urls for to allow file download within CUH & the LGLs.
> ```

Done
___
*[`src/eggd_artemis.py` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwGDXA-Nw3cj1fYBJJ:-NGzA_qdAiTUutnD8ReW:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L2)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

1.0.0
</blockquote></details>

Done
___
*[`src/eggd_artemis.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwGItIBuqEa417nrS8:-NGzAYvNERylhvxEzt78:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L12)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could we remove this stuff which is added by the wizard?
</blockquote></details>

Done
___
*[`src/eggd_artemis.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwGdB69qQ1wgat87WQ:-NGzAcgH7FXKACOf32ye:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L37)):*
> ```Python
> 
>     Returns:
>         snv_data (dict): Nested ictionary of files with sample name
> ```

Done
___
*[`src/eggd_artemis.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwHc3U7zESFn44s4PL:-NGzBJGUAFPs-aBsGfnn:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L154)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Would it be better to look for `sample_` so that X123 doesn't match X1234?

Should never happen, but no reason not to defend against this
</blockquote></details>

Done
___
*[`src/eggd_artemis.py` line 364 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NGwJOuV5vNNg5Y8hjqF:-NGzAtZY9gj0-cjHXHU_:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/44dc4002df7721746cc43477d4879a342ebc1d6b/src/eggd_artemis.py#L364)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Newline before each sample would make the output format a little nicer imo
</blockquote></details>

Done

**Review by mattgarner — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @Addy81 and @mattgarner)

___
*[`src/eggd_artemis.py` line 8 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-BGqYCELwWCB3n5qT:-NH-BGqYCELwWCB3n5qU:b-sidx3f) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L8)):*
> ```Python
> import dxpy
> import datetime
> import subprocess
> ```

unused import?



_Code quote:_
```Python
import subprocess
```
___
*[`src/eggd_artemis.py` line 125 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-B2rpAHmjapPwcgN-:-NH-B2rpAHmjapPwcgN0:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L125)):*
> ```Python
> 
>     Returns:
>         cnv_data (dict): Nested ictionary of files with sample name
> ```

typo



_Code quote:_
```Python
 ictionary
```
___
*[`src/eggd_artemis.py` line 175 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-Ba3r5UxvPU2aFBZP:-NH-Ba3r5UxvPU2aFBZQ:b-y7xeb7) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L175)):*
> ```Python
>     """
>     for k,v in gcnv_output_dict.items():
>         if k.endswith("excluded_intervals.bed"):
> ```

if the gcnv app had no regions it excluded from calling, would this file just not be present?



_Code quote:_
```Python
excluded_intervals.bed")
```
___
*[`src/eggd_artemis.py` line 194 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-BjtZDU1jC9DLO4qk:-NH-BjtZDU1jC9DLO4ql:b-58so6z) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L194)):*
> ```Python
>     # Find MultiQC jobs in the project
>     multiqc_reports=list(dxpy.bindings.search.find_jobs(
>             #executable="eggd_MultiQC",
> ```

needed?



_Code quote:_
```Python
#executable="eggd_MultiQC"
```
___
*[`src/eggd_artemis.py` line 343 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-CAb30oT0ljPrTTPE:-NH-CAb30oT0ljPrTTPF:baj01lo) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L343)):*
> ```Python
>     expiry = datetime.timedelta(days=14)
> 
>     expiry_date=(datetime.datetime.strptime(datetime.datetime.now().strftime('%Y-%m-%d'), '%Y-%m-%d') + datetime.timedelta(seconds=604800)).strftime('%Y-%m-%d')
> ```

length:
```
expiry_date=(
        datetime.datetime.strptime(datetime.datetime.now().strftime('%Y-%m-%d'),
        '%Y-%m-%d') + datetime.timedelta(seconds=604800)).strftime('%Y-%m-%d')
```



_Code quote:_
```Python
expiry_date=(datetime.datetime.strptime(datetime.datetime.now().strftime('%Y-%m-%d'), '%Y-%m-%d') + datetime.timedelta(seconds=604800)).strftime('%Y-%m-%d')
```

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`src/eggd_artemis.py` line 8 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-BGqYCELwWCB3n5qT:-NH-Dy4R4P4orJK8i_T2:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L8)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

unused import?
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 125 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-B2rpAHmjapPwcgN-:-NH-DzUW0UBVdevAAf2l:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L125)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done
___
*[`src/eggd_artemis.py` line 175 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-Ba3r5UxvPU2aFBZP:-NH-EIBL0R0LAoq6pebC:bqc0o2y) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L175)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if the gcnv app had no regions it excluded from calling, would this file just not be present?
</blockquote></details>

File will always exist even if empty for now.
___
*[`src/eggd_artemis.py` line 194 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-BjtZDU1jC9DLO4qk:-NH-E0id2aO0jWhy_L9E:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L194)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 343 at r4](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1#-NH-CAb30oT0ljPrTTPE:-NH-E1eXAraHbM-U7apO:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/2de744c5fa28232205128fbe5d3bb91384fc5e29/src/eggd_artemis.py#L343)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

length:
```
expiry_date=(
        datetime.datetime.strptime(datetime.datetime.now().strftime('%Y-%m-%d'),
        '%Y-%m-%d') + datetime.timedelta(seconds=604800)).strftime('%Y-%m-%d')
```
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 2 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @Addy81)

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Pull request merged**
