### PR TITLE
Gcnv 95 v1.1.0

### LINKED ISSUE #3: Date created gets messed up in excel
Scientists want to be able to open this in excel, the date created doesn't resolve correctly when opened with it.

image

### PR DESCRIPTION
**Pull request by Addy81**
* Fixes #3 by changing it to just the date and removing the time created.
* Adds cnv sessions created and uploaded to dnanexus.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @Addy81)

___
*[`src/eggd_artemis.py` line 291 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7bqTM3RGkZjt0FnYI:-NI7bqTM3RGkZjt0FnYJ:b8y65ss) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L291)):*
> ```Python
>     """ Create a session file for IGV
> 
>     Args:
> ```

missing args
___
*[`src/eggd_artemis.py` line 300 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7buE15uzS9xhb7f1M:-NI7buE15uzS9xhb7f1N:b-jhlrxu) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L300)):*
> ```Python
> 
>     Returns:
>         session_file (string): IGV session file URL
> ```

missing a return
___
*[`src/eggd_artemis.py` line 338 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7c0--2a4BTgojBcVD:-NI7c0--2a4BTgojBcVE:b-58so6z) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L338)):*
> ```Python
>             track['indexURL'] = order_map[order]['indexURL']
>         #if track['order'] == 6:
>             #track['highlightSamples'][sample] = "red"
> ```

needed?



_Code quote:_
```Python
        #if track['order'] == 6:
            #track['highlightSamples'][sample] = "red"
```
___
*[`src/eggd_artemis.py` line 343 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7c2zJ7nXuITIScFP3:-NI7c2zJ7nXuITIScFP4:bauhe18) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L343)):*
> ```Python
> 
> 
>     output_name = sample + "_igv.json"
> ```

`f"{sample}_igv.json"`



_Code quote:_
```Python
sample + "_igv.json"
```
___
*[`src/eggd_artemis.py` line 353 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7cJhB91bGs9Sn8mlO:-NI7cJhB91bGs9Sn8mlP:b-2qbm0p) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L353)):*
> ```Python
>     # Get output folder set for this job
>     job_output = dxpy.bindings.dxjob.DXJob(DX_JOB_ID).describe()['folder']
>     if job_output == '/':
> ```

can't this just be `output_folder = f'{job_output}/igv_sessions'`?



_Code quote:_
```Python
    if job_output == '/':
        output_folder = '/igv_sessions'
    else:
        output_folder = f'{job_output}/igv_sessions'
```
___
*[`src/eggd_artemis.py` line 376 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7cYMh7EcQw65i_DIt:-NI7cYMh7EcQw65i_DIu:b-ulwnk2) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L376)):*
> ```Python
>     sessions_list.append(session_file)
> 
>     session_file_id = list(dxpy.bindings.search.find_data_objects(
> ```

is `session_file` above not the file ID of the object uploaded? whats the need to search for it?



_Code quote:_
```Python
    session_file_id = list(dxpy.bindings.search.find_data_objects(
        project=DX_PROJECT,
        name=output_name,
        name_mode='exact'))[0]
```
___
*[`src/eggd_artemis.py` line 384 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7cgCH4NB5jy0be5xj:-NI7cgCH4NB5jy0be5xk:b-58so6z) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L384)):*
> ```Python
>                 dxid=session_file_id['id'], project=DX_PROJECT)
> 
>     #session_info.close(block=True)
> ```

needed?



_Code quote:_
```Python
   #session_info.close(block=True)
```
___
*[`src/eggd_artemis.py` line 447 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7ckQYEhgV-pNyrs9e:-NI7ckQZ8Ghv4znZ9lpn:b3ha3ev) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L447)):*
> ```Python
>             # Get excluded intervals file
>             excluded_intervals = get_excluded_intervals(gcnv_job_info)
>             ex_intervals_url = make_url(excluded_intervals,DX_PROJECT,url_duration)
> ```

spaces after commas pls



_Code quote:_
```Python
excluded_intervals,DX_PROJECT,url_duration)
```
___
*[`src/eggd_artemis.py` line 455 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7cphYAfHzcV9KTji2:-NI7cphYAfHzcV9KTji3:b152mug) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L455)):*
> ```Python
>     logger.info("Making URLs for additional files")
>     # If a bed file is provided, add to a link to the output
>     if bed_file is not None:
> ```

this can just be `if bed_file:` unless you explicitly need to differentiate between `None` and `False` etc 



_Code quote:_
```Python
if bed_file is not None:
```
___
*[`src/eggd_artemis.py` line 512 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7drsFDJrEMeWM1XDW:-NI7drsFDJrEMeWM1XDX:bhthld0) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L512)):*
> ```Python
>             # For each sample, write out the available sample URLs
>             for sample,details in data.items():
> ```

if you want to speed this up and parallelise it, I'd add the below lines that call `make_url()` into its own function (something like `make_all_urls()`) that takes sample and details together as a tuple input and returns a dict of urls including the sample ID, something like:

```
{
    "sample1": {
        "bam_url": "https//:ekrhfgvnbkjernf",
        "bai_url": "https://emhrfbnrwk"
    }
}
```

Then calling in with concurrent.futures would be something like this:

```
sample_urls = []

with concurrent.futures.ThreadPoolExecutor(max_workers=48) as executor:
    concurrent_jobs = {executor.submit(make_all_urls, sample, details): (sample, details) for sample, details in file_ids.items()}
    for future in concurrent.futures.as_completed(concurrent_jobs):
    try:
        data = future.result()
        sample_urls.append(data)
    except Exception as exc:
         # catch any errors that might get raised during querying
          print(f"Error getting data for {concurrent_jobs[future]}: {exc}")
```

then you'd have a list of dicts with the sample ID and all urls in, that you can then iterate over and write to file as you're doing in this section
___
*[`src/eggd_artemis.py` line 522 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7dGZ28kIatbFTSmkD:-NI7dGZ28kIatbFTSmkE:b-9ii33e) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/c47b1a97227cbae0b7f473f1bd541f0c537bb867/src/eggd_artemis.py#L522)):*
> ```Python
>                     f.write(f"CNV variant report:\t{make_url(details['CNV variant report'],DX_PROJECT,url_duration)}\n\n")
> 
>                 bam = make_url(details['Alignment BAM'],DX_PROJECT,url_duration)
> ```

comma space



_Code quote:_
```Python
,DX_PROJECT,url_duration)
```

**Comment by Addy81** [comment]
Job after PR changes: https://platform.dnanexus.com/projects/GJFBY1046FxB9j1G4jPPg3kV/monitor/job/GK3bx0846Fx0x33G6bp94kp1

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4)* status: 2 of 3 files reviewed, 12 unresolved discussions (waiting on @Addy81)

___
*[`src/eggd_artemis.py` line 382 at r3](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4#-NI7qOVM7Qkt6RFJs_2_:-NI7qOVM7Qkt6RFJs_2a:b-oby5mz) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/94045ac8423886ee552956bbdcd9124e1dbe768e/src/eggd_artemis.py#L382)):*
> ```Python
>         tags=[expiry_date],
>         wait_on_close=True)
>     print()
> ```

empty print



_Code quote:_
```Python
print()
```

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Addy81)

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Pull request merged**
